name: Auto Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Set Version
        run: echo "VERSION=v1.0.1" >> $GITHUB_ENV

      - name: Check for GX_TOKEN Secret
        id: check_token_secret
        run: echo "GX_TOKEN is ${{ secrets.GX_TOKEN }}"
        continue-on-error: true

      - name: Check Existing Release
        id: check_release
        run: |
          if [[ -n "${{ secrets.GX_TOKEN }}" ]]; then
            TAG_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/${{ env.VERSION }})
            if [[ "$TAG_EXISTS" -eq 200 ]]; then
              echo "Release with tag ${{ env.VERSION }} already exists."
              echo "RELEASE_EXISTS=true" >> $GITHUB_ENV  # Set environment variable
            fi
          else
            echo "GX_TOKEN secret not available. Skipping release check."
          fi

      - name: Create Release
        if: env.RELEASE_EXISTS != 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GX_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            Release ${{ env.VERSION }}